// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/components/layouts/404.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    Default: typeof import('./src/components/layouts/default.vue')['default']
    Empty: typeof import('./src/components/layouts/empty.vue')['default']
    MdiEmail: typeof import('virtual:vite-icons/mdi/email')['default']
    MdiGithub: typeof import('virtual:vite-icons/mdi/github')['default']
    MdiLinkedin: typeof import('virtual:vite-icons/mdi/linkedin')['default']
    MdiMapMarker: typeof import('virtual:vite-icons/mdi/map-marker')['default']
    MdiOpenInNew: typeof import('virtual:vite-icons/mdi/open-in-new')['default']
    MdiThemeLightDark: typeof import('virtual:vite-icons/mdi/theme-light-dark')['default']
    MdiTranslate: typeof import('virtual:vite-icons/mdi/translate')['default']
    README: typeof import("./src/components/README.md")["default"]
  }
}

export { }
