import fs from "node:fs"
import path from "node:path"

const ContentIcons = (options?: { contentDir?: string }) => {
  let contentDir: string
  let outFile: string
  let lastOutput: string | null = null

  const regenerate = () => {
    const icons = scanContentDir(contentDir)
    const output = generateFile(icons)

    // Only write if content changed
    if (output === lastOutput) return
    lastOutput = output

    // Ensure directory exists
    fs.mkdirSync(path.dirname(outFile), { recursive: true })
    fs.writeFileSync(outFile, output, "utf-8")
  }

  return {
    name: "vite-plugin-content-icons",

    configResolved(config: { root: string }) {
      const root = config.root
      contentDir = options?.contentDir ?? path.resolve(root, "content")
      outFile = path.resolve(root, "src/lib/content-icons/generated.ts")
    },

    buildStart() {
      regenerate()
    },

    configureServer(server: {
      watcher: {
        add: (path: string) => any
        on: (event: string, fn: (path: string) => void) => void
      }
    }) {
      // Watch the content directory for changes
      server.watcher.add(contentDir)

      const regenerateOnChange = (filePath: string) => {
        if (filePath.startsWith(contentDir)) {
          regenerate()
        }
      }

      server.watcher.on("change", regenerateOnChange)
      server.watcher.on("add", regenerateOnChange)
      server.watcher.on("unlink", regenerateOnChange)
    },

    closeBundle() {
      lastOutput = null
    },
  }
}

const ICON_REGEX = /~icons\/([a-z][a-z0-9-]*)\/([a-z][a-z0-9-]*)/g

const toComponentName = (iconPath: string): string => {
  // "~icons/tabler/device-gamepad-3" → "TablerDeviceGamepad3"
  return iconPath
    .replace(/^~icons\//, "")
    .split("/")
    .map((part) =>
      part
        .split("-")
        .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
        .join(""),
    )
    .join("")
}

const scanContentDir = (contentDir: string): Set<string> => {
  const icons = new Set<string>()

  const scan = (dir: string) => {
    const entries = fs.readdirSync(dir, { withFileTypes: true })
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name)
      if (entry.isDirectory()) {
        scan(fullPath)
      } else if (entry.isFile()) {
        const content = fs.readFileSync(fullPath, "utf-8")
        let match: RegExpExecArray | null
        // Reset lastIndex for global regex
        ICON_REGEX.lastIndex = 0
        while ((match = ICON_REGEX.exec(content)) !== null) {
          icons.add(match[0])
        }
      }
    }
  }

  scan(contentDir)
  return icons
}

const generateFile = (icons: Set<string>): string => {
  const sorted = [...icons].sort()

  if (sorted.length === 0) {
    return [
      "// AUTO-GENERATED by content-icons plugin — DO NOT EDIT",
      'import type { Component } from "solid-js"',
      "",
      "export const contentIcons: Record<string, Component> = {}",
      "",
    ].join("\n")
  }

  const imports = sorted
    .map((iconPath) => {
      const componentName = toComponentName(iconPath)
      return `import ${componentName} from "${iconPath}"`
    })
    .join("\n")

  const entries = sorted
    .map((iconPath) => {
      const componentName = toComponentName(iconPath)
      return `  "${iconPath}": ${componentName}`
    })
    .join(",\n")

  return [
    "// AUTO-GENERATED by content-icons plugin — DO NOT EDIT",
    'import type { Component } from "solid-js"',
    "",
    imports,
    "",
    "export const contentIcons: Record<string, Component> = {",
    entries,
    "}",
    "",
  ].join("\n")
}

export default ContentIcons
