name: Supabase Keepalive Ping

on:
  schedule:
    - cron: "0 0 */3 * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-20.04

    steps:
      - name: Ping Supabase to keep it from pausing
        id: ping
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://msfvkoblamagehrpbmtw.supabase.co/rest/v1/messages?select=*
          method: GET
          customHeaders: '{"apikey": "${{ secrets.PUBLIC_SUPABASE_KEY }}", "Authorization": "${{ secrets.PUBLIC_SUPABASE_KEY }}"}'
