name: Supabase Keepalive Ping

# Periodically make an API request to Supabase to prevent the project from pausing
# The request updates a row of the Ping table

on:
  # schedule:
  #   - cron: "0 0 */3 * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-20.04

    steps:
      - name: Set timestamp
        id: set_timestamp
        run: echo "::set-output name=TIMESTAMP::$(date)"

      - name: Ping Supabase
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://msfvkoblamagehrpbmtw.supabase.co/rest/v1/ping?id=eq.1
          method: PATCH
          customHeaders: |
            {
              "apikey": "${{ secrets.PUBLIC_SUPABASE_KEY }}",
              "Authorization": "${{ secrets.PUBLIC_SUPABASE_KEY }}",
              "Content-Type": "application/json",
              "Prefer": "return=representation"
            }
          data: |
            { "content": "${{ steps.set_timestamp.outputs.TIMESTAMP }}" }
